# Build
FROM node:18-alpine as build

# node modules to $PATH
WORKDIR /app
ENV PATH /app/node_modules/.bin:${PATH}

# deps
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
RUN npm install

COPY . ./
RUN npm run build

# Prod
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
